# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_point_to_poly_C_ <- function(point, polygon, ABC) {
    .Call('RShapeTarget_dist_point_to_poly_C_', PACKAGE = 'RShapeTarget', point, polygon, ABC)
}

